export { default as Html } from './html-5.png'
export { default as Css } from './css-3.png'
export {default as Js} from './js.png'
export {default as Php} from './php.png'
export { default as Java } from './java.png'
export { default as CSharp } from './c-sharp.png'
export {default as CPlus2} from './c-.png'
export { default as Mysql } from './mysql.png'
export { default as ReactIcon } from './react.svg'
export {default as BootstrapIcon} from './bootstrap.png'
export {default as TailwindCss} from './tailwind.svg'
export { default as Word } from './word.png'
export {default as Excel} from './excel.png'
export {default as PowerPoint} from './powerpoint.png'
export {default as Access} from './microsoft-access.png'
export {default as Basic} from './visual-basic.png'
export {default as VsCode} from './vs-code.png'
export {default as NetBeans} from './netbeans.png'
export {default as Photoshop} from './photoshop.png'
export {default as Illustrator} from './illustrator.png'
export {default as Xd} from './xd.png'
export {default as Reactboostrap} from './reactbootstrap.svg'
